/******************************************************************************
Find the Difference
-------------------

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

*******************************************************************************/

class Solution {
    public char findTheDifference(String s, String t) {
        int sumS = 0;
        int sumT = 0;

        // Calculate the sum of ASCII values of characters in string s
        for (int i = 0; i < s.length(); i++) {
            sumS += (int) s.charAt(i);
        }

        // Calculate the sum of ASCII values of characters in string t
        for (int i = 0; i < t.length(); i++) {
            sumT += (int) t.charAt(i);
        }

        // Find the difference between the sums
        int difference = sumT - sumS;

        // Convert ASCII value back to char
        return (char) difference;
    }
}
